# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
# @help: https://docs.docker.com/compose/compose-file

name: my_music_tool

services:
  go:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      target: deps
    image: ghcr.io/fruzitent/my_music_tool-go:latest
    ports:
      - published: 8080
        target: 8080
    pull_policy: if_not_present
    restart: always
    volumes:
      - type: volume
        source: go_data
        target: /workspaces/
        volume:
          nocopy: true

volumes:
  go_data:
